Dear {{ $user->name }},
<br>
<br>
We hope you're having a great weekend! We're excited to share with you the last 5 ideas generated by the AI on {{config('app.name')}}.
These ideas are designed to inspire and motivate you to build something amazing.
<br>
<ul>
    @foreach ($ideas as $idea)
        <li>
            <a href="{{ route('app.ideas.catalog.idea', [
                        'id' => $idea->id,
                        'title' => str_replace(' ', '-', strtolower($idea->title)),
                        'category' => $idea->category->code]) }}">{{ $idea['title'] }}
            </a>
        </li>
    @endforeach
</ul>
<br>
<br>
To view the full details of each idea, including suggested features, benefits for users, possible pricing, and existing competitors, simply click on the idea title.
<br>
<br>
We hope you find these ideas to be valuable and inspiring. If you have any questions or feedback, please don't hesitate to contact us.
<br>
<br>
Thank you for choosing <a href="{{config('app.url')}}">{{config('app.name')}}</a>, and happy building!
<br>
<br>
Best regards,
<br>
Didier
<br>
Founder of {{config('app.name')}}